### ISSUE TITLE
Не удалось загрузить initdata.sql

### ISSUE THREAD

**Issue by Bespalov-AV** [leon-mbs/zstore#5]
Приветствую!
Развернул на хостинге ваше приложение.
При попытки загрузить initdata.sql после db.sql получаю ошибку.

```
Ошибка
Статический анализ:

Найдено 2 ошибок при анализе.

Неожиданное начало выражения. (near "ET" at position 0)
Неизвестный оператор. (near "NAMES" at position 3)
SQL запрос:

ET NAMES 'utf8'

Ответ MySQL: Документация

#1064 - У вас ошибка в запросе. Изучите документацию по используемой версии MySQL на предмет корректного синтаксиса около 'ET NAMES 'utf8'' на строке 1
```
В итоге данных в таблицах нет и нет видов документов в меню

**Comment by leon-mbs** [comment]
Re: [leon-mbs/zstore] Не удалось загрузить initdata.sql (#5)



Hello, Алексей,

потерялась буковка

должно  быть SET NAMES 'utf8';


я пару дней назад обновлял  версию - возмите последнюю


Sunday, March 24, 2019, 5:55:10 AM, you wrote:





Приветствую!
Развернул на хостинге ваше приложение.
При попытки загрузить initdata.sql после db.sql получаю ошибку.
Ошибка
Статический анализ:

Найдено 2 ошибок при анализе.

Неожиданное начало выражения. (near "ET" at position 0)
Неизвестный оператор. (near "NAMES" at position 3)
SQL запрос:

ET NAMES 'utf8'

Ответ MySQL: Документация

#1064 - У вас ошибка в запросе. Изучите документацию по используемой версии MySQL на предмет корректного синтаксиса около 'ET NAMES 'utf8'' на строке 1
В итоге данных в таблицах нет и нет видов документов в меню
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.





--
Best regards,
 Leon
           leon.mbs@gmail.com
                     mailto:leon.mbs@gmail.com
